### ISSUE TITLE
./inc.h:28:10: fatal error: 'cstdint' file not found

### ISSUE THREAD

**Issue by Xoooo** [griwes/reaveros-iteration1#12]
ubutu64@ubutu64:~/MyCode/reaveros-iteration1$ make hdd
cd loader/hdd; \
yasm stage1.asm -o ../../builds/stage1.img
cd loader/hdd/stage2; \
yasm stage2.asm -o ../../../builds/stage2.img
cd loader/booter; \
make; \
mv builds/booter.img ../../builds/
make[1]: Entering directory '/home/ubutu64/MyCode/reaveros-iteration1/loader/booter'
clang++ -m32 -c -Wall -Wextra -pedantic -Werror -nostdlib -fno-exceptions -fno-rtti -fno-stack-protector -std=c++1y -mno-sse -mno-sse2 -mno-sse3 -mno-sse4 -mno-avx -ffreestanding -Os -stdlib=libc++ -fno-builtin -MD -target i686-none-elf -integrated-as -Weffc++ memory/manager.cpp -o memory/manager.o -I. -include inc.h
In file included from <built-in>:328:
In file included from <command line>:1:
**./inc.h:28:10: fatal error: 'cstdint' file not found**
# include <cstdint>

```
     ^
```

1 error generated.
Makefile:19: recipe for target 'memory/manager.o' failed
make[1]: **\* [memory/manager.o] Error 1
make[1]: Leaving directory '/home/ubutu64/MyCode/reaveros-iteration1/loader/booter'

I do not have to solve this problem through a number of methods...

**Comment by griwes** [comment]
Do you have libc++ installed?

Also beware that this repository is here for historical value only (hence why I'm closing this); I do not intend to work on it anymore, and rather rewrite all this without some of the dubious decisions I made the first few times around in griwes/reaveros, but only after some of the stuff I need (namely a build system that I can like; see griwes/despayre) is also finished.

**Comment by Xoooo** [comment]
Thanks : )
