### ISSUE TITLE
What is raf ?

### ISSUE THREAD

**Issue by k1rn1l** [griwes/reaveros-iteration1#13]
**raf -c init.srv -o ../builds/initrd.img**

Because of the lack of this program, the compilation process can not continue

**Comment by griwes** [comment]
It's an internal tool, not really available anywhere anymore. If you _really_ want to build this, please use the latest tagged release; as I wrote elsewhere, I am not going to work on the code in this repository any further.

By the way, I've got two tickets within the last week or so; is there any specific reason for how suddenly seemingly popular this got, or did you randomly stumble upon this project?

**Comment by Fluray** [comment]
Excellent project will be granted attention.
I tried to focus all of the kernel project which was written by c++ on github.

**Comment by k1rn1l** [comment]
Excellent project will be granted attention.
I tried to focus all of the kernel project written by c++ on github.
